-- The product event stream (`KPI-2`), and the index the audit log viewer
-- (`ADM-7`) reads.
--
-- ── WHY A TABLE AND NOT AN ANALYTICS VENDOR ─────────────────────────────────
--
-- TRD §3 is explicit: start with a `product_events` table in the same Postgres
-- and a weekly SQL report; graduate when volume demands it, not when a vendor
-- suggests it. At 5,000 jobs a year this table gains roughly 30,000 rows
-- annually — four orders of magnitude below where the decision changes.
--
-- ── WHY THE EMITTER IS A TRIGGER AND NOT APPLICATION CODE ───────────────────
--
-- The same argument `sql/rls.sql` already makes for `audit_log`, and it is the
-- argument that decides this: *an audit log the application can forget to write
-- is not an audit log.* An event stream has the identical failure mode, and a
-- worse consequence — a missing audit row is noticed when somebody looks for
-- it, a missing event row silently changes a number on the owner's dashboard
-- and nobody ever knows the denominator was wrong.
--
-- Concretely, writing these in TypeScript would mean:
--
--   * every future code path that transitions a job has to remember to emit,
--     including the ones written by somebody who has never read this file;
--   * a hand-repair during an incident (`update jobs set status = …`) produces
--     no event, so the one week where the funnel matters most is the week with
--     a hole in it;
--   * the emit and the business write are two statements that can be separated
--     by a `return` — the transactional-enqueue pattern in `packages/notify`
--     exists precisely because that separation kept happening.
--
-- A trigger has none of those. It fires inside the same transaction as the
-- write, so an event exists if and only if the change it describes was
-- committed, and it cannot be forgotten by code that has not been written yet.
--
-- ── WHAT THIS DELIBERATELY DOES NOT CLAIM ───────────────────────────────────
--
-- `KPI-2` names eleven event families. FIVE of them are emitted here — lead
-- stage changes, job status changes, quote sent/decided, invoice issued and
-- payment recorded — plus `contract_status_changed`, which `KPI-2` does not ask
-- for and which G10's renewal rate needs.
--
-- The other SIX have no emitter: the quote-form funnel, assignment-warning
-- overrides, portal actions, authentication events, ATS stage changes and
-- field-app sync health. They either leave no row transition to hang a trigger
-- on (a form abandoned at step two writes nothing) or they belong to tables
-- that do not exist yet.
--
-- They are declared anyway, in `PRODUCT_EVENT_NAMES` in
-- `packages/db/src/domain/reporting.ts`, with `emitter: "none"`. That is the
-- point: a report that shows `portal_action  0` looks identical to one where
-- portal actions are simply not instrumented, and the first is a business fact
-- while the second is a gap in the software. The registry keeps them apart, and
-- the weekly report prints the uninstrumented list rather than a row of zeros.

-- ── product_events ──────────────────────────────────────────────────────────
--
-- `tenant_id` first, so the generic policy loop in `sql/rls.sql` covers this
-- table the moment it is re-run rather than when somebody remembers.
CREATE TABLE IF NOT EXISTS "product_events" (
	"tenant_id" uuid NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	-- Stable machine key, snake_case, chosen from a registry rather than typed
	-- at the call site. Reports group on this column, so the same rule that
	-- governs `lead_disposition_reasons.code` in 0012 governs it: a name that
	-- can be typed by hand becomes five spellings of one event and the report
	-- that was the entire point of collecting it cannot group them.
	"event_name" varchar(48) NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	-- Nullable, and usually null for the trigger-emitted events. A PPM job
	-- generated by cron has no actor, and recording the system as a user would
	-- put a person's name against a change they did not make.
	"actor_user_id" uuid,
	"actor_kind" varchar(16) DEFAULT 'user' NOT NULL,
	"entity_type" varchar(48),
	"entity_id" uuid,
	-- Everything the event-specific question needs, and nothing that belongs in
	-- a column. Deliberately NOT a place for PII: these rows outlive the records
	-- they describe, and a retention purge that cannot find a name cannot delete
	-- it. Amounts, statuses, durations and slugs only.
	"properties" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "product_events_tenant_fk" FOREIGN KEY ("tenant_id")
		REFERENCES "tenants"("id") ON DELETE cascade,
	CONSTRAINT "product_events_actor_fk" FOREIGN KEY ("actor_user_id")
		REFERENCES "users"("id") ON DELETE set null
);--> statement-breakpoint

-- The weekly report's query: one event family over a window, per tenant.
CREATE INDEX IF NOT EXISTS "product_events_name_time_idx"
	ON "product_events" USING btree ("tenant_id", "event_name", "occurred_at");--> statement-breakpoint

-- "What happened to this record?" — the funnel questions in PRD §7.1 that
-- measure one entity's progress (G2 lead response, G6 quote cycle time) all
-- read the events for a single id in time order.
CREATE INDEX IF NOT EXISTS "product_events_entity_idx"
	ON "product_events" USING btree ("tenant_id", "entity_type", "entity_id", "occurred_at");--> statement-breakpoint

-- ── The emitter ─────────────────────────────────────────────────────────────
--
-- SECURITY DEFINER, exactly like `app_audit_trigger`, and for two reasons.
--
-- First, `tenant_id` comes from the row being written, not from
-- `app_current_tenant()`. The GUC is unset during migrations, during the seed,
-- and inside `withoutTenantBoundary`, and a NOT NULL violation raised from a
-- trigger would turn "this deployment has an event stream" into "this
-- deployment cannot write a job". The row always knows its own tenant; the
-- session does not always know it.
--
-- Second, the insert has to succeed under a policy the writing session may not
-- satisfy — the seed connects as the owner with no tenant context at all.
--
-- The `product_events_append` policy below is the belt to this braces, for the
-- same reason `audit_append` exists: relying on the definer holding BYPASSRLS
-- is relying on a property of the deployment's role grants rather than on
-- something written down in this repository.
CREATE OR REPLACE FUNCTION app_product_event(
	p_tenant_id uuid,
	p_event_name text,
	p_entity_type text,
	p_entity_id uuid,
	p_properties jsonb
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
	INSERT INTO public.product_events (
		tenant_id, event_name, occurred_at, actor_user_id, actor_kind,
		entity_type, entity_id, properties
	) VALUES (
		p_tenant_id,
		p_event_name,
		now(),
		app_current_user(),
		COALESCE(NULLIF(current_setting('app.actor_kind', true), ''), 'user'),
		p_entity_type,
		p_entity_id,
		COALESCE(p_properties, '{}'::jsonb)
	);
END
$$;--> statement-breakpoint

-- Read scoped to the tenant; append unrestricted.
--
-- The asymmetry is identical to `audit_log`'s and has the same justification:
-- the writer is a definer function that derives the tenant from the row, so a
-- restrictive WITH CHECK would only ever block legitimate writes made outside a
-- tenant transaction. The generic loop in `sql/rls.sql` adds the FOR ALL
-- `tenant_isolation` policy on top of this one when it is re-run, which is what
-- scopes SELECT, UPDATE and DELETE.
--
-- NOT hardened append-only. `audit_log` has UPDATE and DELETE revoked from
-- `meridian_app` in the final block of `sql/rls.sql`; this table does not, and
-- saying so is better than implying an evidential guarantee it does not carry.
-- `product_events` is telemetry, not evidence — the legally significant trail
-- is `audit_log`, and that is the one with the revoke.
ALTER TABLE public.product_events ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.product_events FORCE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS product_events_append ON public.product_events;--> statement-breakpoint
CREATE POLICY product_events_append ON public.product_events
	FOR INSERT WITH CHECK (true);--> statement-breakpoint

-- ── Lead events (G1 capture, G2 response time) ──────────────────────────────
--
-- `channel` rather than `source` in the properties, because `LEAD-1` constrains
-- the first and not the second, and a funnel grouped on an unconstrained column
-- is the free-text problem 0012 exists to prevent.
CREATE OR REPLACE FUNCTION app_product_event_leads() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		PERFORM app_product_event(NEW.tenant_id, 'lead_created', 'lead', NEW.id, jsonb_build_object(
			'channel', NEW.channel,
			'source', NEW.source,
			'service_slug', NEW.service_slug,
			'utm_source', NEW.utm_source,
			'utm_medium', NEW.utm_medium,
			'utm_campaign', NEW.utm_campaign,
			'stage', NEW.stage::text
		));
	ELSIF NEW.stage IS DISTINCT FROM OLD.stage THEN
		-- `minutes_since_created` is what G2 measures — created to first stage
		-- change — and it is computed here rather than by joining back to the
		-- lead later, because the lead row can be deleted and the target is a
		-- median over a window rather than a per-row lookup.
		PERFORM app_product_event(NEW.tenant_id, 'lead_stage_changed', 'lead', NEW.id, jsonb_build_object(
			'from', OLD.stage::text,
			'to', NEW.stage::text,
			'channel', NEW.channel,
			'minutes_since_created',
			  GREATEST(0, (EXTRACT(epoch FROM (now() - NEW.created_at)) / 60)::int)
		));
	END IF;
	RETURN NEW;
END
$$;--> statement-breakpoint

DROP TRIGGER IF EXISTS product_event_leads ON public.leads;--> statement-breakpoint
CREATE TRIGGER product_event_leads
	AFTER INSERT OR UPDATE ON public.leads
	FOR EACH ROW EXECUTE FUNCTION app_product_event_leads();--> statement-breakpoint

-- ── Job events (G3 time to dispatch, G11 first-time fix) ────────────────────
CREATE OR REPLACE FUNCTION app_product_event_jobs() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		PERFORM app_product_event(NEW.tenant_id, 'job_created', 'job', NEW.id, jsonb_build_object(
			'status', NEW.status::text,
			'priority', NEW.priority::text,
			'source', NEW.source::text,
			'service_slug', NEW.service_slug,
			'is_revisit', NEW.is_revisit
		));
	ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
		PERFORM app_product_event(NEW.tenant_id, 'job_status_changed', 'job', NEW.id, jsonb_build_object(
			'from', OLD.status::text,
			'to', NEW.status::text,
			'priority', NEW.priority::text,
			'service_slug', NEW.service_slug,
			'outcome_code', NEW.outcome_code,
			'is_revisit', NEW.is_revisit,
			'minutes_since_created',
			  GREATEST(0, (EXTRACT(epoch FROM (now() - NEW.created_at)) / 60)::int),
			-- Non-null only when the SLA clock was set and the deadline has
			-- passed. The dashboard counts breaches from `jobs` directly; this
			-- is here so a historical breach survives the job being closed.
			'breached_response',
			  NEW.respond_by_at IS NOT NULL
			  AND NEW.first_response_at IS NULL
			  AND NEW.respond_by_at < now()
		));
	END IF;
	RETURN NEW;
END
$$;--> statement-breakpoint

DROP TRIGGER IF EXISTS product_event_jobs ON public.jobs;--> statement-breakpoint
CREATE TRIGGER product_event_jobs
	AFTER INSERT OR UPDATE ON public.jobs
	FOR EACH ROW EXECUTE FUNCTION app_product_event_jobs();--> statement-breakpoint

-- ── Quote events (G5 conversion, G6 cycle time) ─────────────────────────────
--
-- `hours_to_decision` is measured from `sent_at`, not from `created_at`. A
-- quote drafted on Monday and sent on Thursday took the customer whatever time
-- they took; counting the three days it sat in a draft makes the sales team
-- look slow at the customer's expense, and G6's target is explicitly
-- "sent → decided".
CREATE OR REPLACE FUNCTION app_product_event_quotes() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
	IF NEW.status IS NOT DISTINCT FROM OLD.status THEN
		RETURN NEW;
	END IF;

	IF NEW.status = 'sent' THEN
		PERFORM app_product_event(NEW.tenant_id, 'quote_sent', 'quote', NEW.id, jsonb_build_object(
			'total_minor', (NEW.total * 100)::bigint,
			'currency', NEW.currency
		));
	ELSIF NEW.status IN ('approved', 'rejected', 'expired') THEN
		PERFORM app_product_event(NEW.tenant_id, 'quote_decided', 'quote', NEW.id, jsonb_build_object(
			'from', OLD.status::text,
			'to', NEW.status::text,
			'total_minor', (NEW.total * 100)::bigint,
			'currency', NEW.currency,
			'hours_to_decision',
			  CASE WHEN NEW.sent_at IS NULL THEN NULL
			       ELSE GREATEST(0, (EXTRACT(epoch FROM (now() - NEW.sent_at)) / 3600)::int)
			  END
		));
	END IF;
	RETURN NEW;
END
$$;--> statement-breakpoint

DROP TRIGGER IF EXISTS product_event_quotes ON public.quotes;--> statement-breakpoint
CREATE TRIGGER product_event_quotes
	AFTER UPDATE ON public.quotes
	FOR EACH ROW EXECUTE FUNCTION app_product_event_quotes();--> statement-breakpoint

-- ── Invoice and payment events (G7 invoice lag, G8 DSO) ─────────────────────
--
-- Fires on INSERT as well as UPDATE, because `createInvoiceFromJob` can insert
-- a row already in `issued` — an UPDATE-only trigger would miss every invoice
-- that was never a draft, which is most of them.
CREATE OR REPLACE FUNCTION app_product_event_invoices() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
	IF TG_OP = 'UPDATE' AND NEW.status IS NOT DISTINCT FROM OLD.status THEN
		RETURN NEW;
	END IF;
	IF TG_OP = 'UPDATE' AND OLD.status <> 'draft' THEN
		-- Already counted when it left draft. `part_paid` and `paid` are payment
		-- events, and `payments` emits those.
		RETURN NEW;
	END IF;
	IF NEW.status = 'draft' THEN
		RETURN NEW;
	END IF;

	PERFORM app_product_event(NEW.tenant_id, 'invoice_issued', 'invoice', NEW.id, jsonb_build_object(
		-- Taxable amount, not total: `taxable_amount` is the tax-exclusive
		-- figure after discount, which is what "revenue" means for the AED 3m
		-- Small Business Relief test. VAT collected on the government's behalf
		-- is not turnover, and a threshold read off VAT-inclusive totals crosses
		-- 5% early.
		'taxable_minor', (NEW.taxable_amount * 100)::bigint,
		'total_minor', (NEW.total * 100)::bigint,
		'currency', NEW.currency,
		'document_type', NEW.document_type,
		-- G7: job signed off → invoice issued.
		'days_since_supply',
		  CASE WHEN NEW.supply_date IS NULL THEN NULL
		       ELSE (CURRENT_DATE - NEW.supply_date)
		  END
	));
	RETURN NEW;
END
$$;--> statement-breakpoint

DROP TRIGGER IF EXISTS product_event_invoices ON public.invoices;--> statement-breakpoint
CREATE TRIGGER product_event_invoices
	AFTER INSERT OR UPDATE ON public.invoices
	FOR EACH ROW EXECUTE FUNCTION app_product_event_invoices();--> statement-breakpoint

CREATE OR REPLACE FUNCTION app_product_event_payments() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
	PERFORM app_product_event(NEW.tenant_id, 'payment_recorded', 'payment', NEW.id, jsonb_build_object(
		'amount_minor', (NEW.amount * 100)::bigint,
		'currency', NEW.currency,
		'method', NEW.method::text,
		'invoice_id', NEW.invoice_id
	));
	RETURN NEW;
END
$$;--> statement-breakpoint

DROP TRIGGER IF EXISTS product_event_payments ON public.payments;--> statement-breakpoint
CREATE TRIGGER product_event_payments
	AFTER INSERT ON public.payments
	FOR EACH ROW EXECUTE FUNCTION app_product_event_payments();--> statement-breakpoint

-- ── Contract events (G10 renewal rate) ──────────────────────────────────────
--
-- The `contracts` table has existed since 0000 with no UI; `CON-1`…`CON-10` are
-- being built in parallel. This trigger reads `status` and nothing else, so it
-- survives whatever columns that work adds.
CREATE OR REPLACE FUNCTION app_product_event_contracts() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
	IF NEW.status IS NOT DISTINCT FROM OLD.status THEN
		RETURN NEW;
	END IF;
	PERFORM app_product_event(NEW.tenant_id, 'contract_status_changed', 'contract', NEW.id, jsonb_build_object(
		'from', OLD.status::text,
		'to', NEW.status::text,
		'annual_value_minor', (NEW.annual_value * 100)::bigint,
		'currency', NEW.currency,
		'ends_on', NEW.ends_on
	));
	RETURN NEW;
END
$$;--> statement-breakpoint

DROP TRIGGER IF EXISTS product_event_contracts ON public.contracts;--> statement-breakpoint
CREATE TRIGGER product_event_contracts
	AFTER UPDATE ON public.contracts
	FOR EACH ROW EXECUTE FUNCTION app_product_event_contracts();--> statement-breakpoint

-- ── ADM-7: the index the audit log viewer reads ─────────────────────────────
--
-- The viewer's default query is "this tenant, this table, newest first", and
-- the three existing indexes cannot serve it. `audit_log_tenant_time_idx` is
-- (tenant_id, occurred_at) with no table_name, so filtering to `invoices`
-- scans every row in the window; `audit_log_record_idx` is (table_name,
-- record_id) with no tenant and no time, so it serves the single-record lookup
-- and nothing else.
--
-- `occurred_at DESC` in the index rather than relying on a backwards scan:
-- Postgres can read either direction, but naming it here documents that the
-- screen is newest-first and keeps the plan stable if a second sort key is ever
-- added.
CREATE INDEX IF NOT EXISTS "audit_log_tenant_table_time_idx"
	ON "audit_log" USING btree ("tenant_id", "table_name", "occurred_at" DESC);
