-- =============================================================================
-- The second-factor surface.
--
-- Run AFTER rls.sql and auth-functions.sql.
--
-- Same bootstrap problem as authentication, same answer. A user proving their
-- second factor has passed their password but has no session, therefore no
-- tenant GUC, therefore no RLS-visible rows. These functions are the only way
-- the application reaches `mfa_challenges`, `user_recovery_codes` and the MFA
-- columns on `users` during that gap.
--
-- Enrolment is deliberately NOT here. A user enrolling is already signed in, so
-- `app_current_user()` resolves and the ordinary `users` policy lets them
-- update their own row — no definer function required, and therefore none
-- written. Every function in this file is a hole in the boundary that an
-- unauthenticated caller can reach, so the bar for adding one is the same as
-- for `app_auth_*`: one step, minimum columns, pinned search_path.
--
-- The rules from auth-functions.sql apply unchanged:
--   1. SET search_path on every function.
--   2. Return the minimum.
--   3. Never trust a tenant_id from the caller.
-- =============================================================================

-- ── Open a challenge after a correct password ──────────────────────────────
-- The caller has already verified the password. This records that a second
-- factor is outstanding and returns nothing but the challenge id; the raw token
-- is generated by the application and only its hash arrives here.
CREATE OR REPLACE FUNCTION app_mfa_begin(
  p_user_id uuid,
  p_tenant_id uuid,
  p_token_hash text,
  p_expires_at timestamptz,
  p_user_agent text,
  p_ip text
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_id uuid;
BEGIN
  -- Housekeeping on the way past. Challenges live five minutes; keeping dead
  -- ones costs nothing but makes the table harder to read during an incident.
  DELETE FROM mfa_challenges WHERE expires_at < now() - interval '1 day';

  INSERT INTO mfa_challenges (user_id, tenant_id, token_hash, expires_at, user_agent, ip_address)
  VALUES (p_user_id, p_tenant_id, p_token_hash, p_expires_at, p_user_agent, p_ip)
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

-- ── Resolve a challenge to what the check needs ────────────────────────────
-- Returns the secret, so it returns nothing else that could widen the blast
-- radius if this function were ever called with a guessed token: no email, no
-- name, no membership detail. A caller who already holds the token learns only
-- what they need to verify a code.
CREATE OR REPLACE FUNCTION app_mfa_resolve(p_token_hash text)
RETURNS TABLE (
  challenge_id uuid,
  user_id uuid,
  tenant_id uuid,
  attempts integer,
  mfa_secret text,
  mfa_last_step bigint
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT c.id, c.user_id, c.tenant_id, c.attempts, u.mfa_secret, u.mfa_last_step
  FROM mfa_challenges c
  JOIN users u ON u.id = c.user_id
  WHERE c.token_hash = p_token_hash
    AND c.consumed_at IS NULL
    AND c.expires_at > now()
    AND u.deleted_at IS NULL
$$;

-- ── Record a wrong code ────────────────────────────────────────────────────
-- Returns the new count so the caller can stop offering retries. Without a
-- ceiling a six-digit code is a million guesses against a live challenge.
CREATE OR REPLACE FUNCTION app_mfa_record_attempt(p_challenge_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_attempts integer;
BEGIN
  UPDATE mfa_challenges
     SET attempts = attempts + 1
   WHERE id = p_challenge_id
  RETURNING attempts INTO v_attempts;

  RETURN coalesce(v_attempts, 0);
END;
$$;

-- ── Consume a challenge on success ─────────────────────────────────────────
-- Marking the challenge and advancing the replay guard happen in one statement
-- pair inside one function, so a code cannot be accepted twice by two requests
-- racing each other: the second finds `consumed_at` already set.
CREATE OR REPLACE FUNCTION app_mfa_complete(p_challenge_id uuid, p_step bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user uuid;
BEGIN
  UPDATE mfa_challenges
     SET consumed_at = now()
   WHERE id = p_challenge_id
     AND consumed_at IS NULL
     AND expires_at > now()
  RETURNING user_id INTO v_user;

  IF v_user IS NULL THEN
    RETURN false;
  END IF;

  -- Never move the guard backwards, in case two steps resolve out of order.
  IF p_step IS NOT NULL THEN
    UPDATE users
       SET mfa_last_step = greatest(coalesce(mfa_last_step, 0), p_step),
           updated_at = now()
     WHERE id = v_user;
  END IF;

  RETURN true;
END;
$$;

-- ── Spend a recovery code ──────────────────────────────────────────────────
-- Single use, enforced by the `used_at IS NULL` predicate on the UPDATE rather
-- than by a read-then-write in application code, so two simultaneous attempts
-- with the same code cannot both succeed.
CREATE OR REPLACE FUNCTION app_mfa_consume_recovery(p_user_id uuid, p_code_hash text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_id uuid;
BEGIN
  UPDATE user_recovery_codes
     SET used_at = now()
   WHERE user_id = p_user_id
     AND code_hash = p_code_hash
     AND used_at IS NULL
  RETURNING id INTO v_id;

  RETURN v_id IS NOT NULL;
END;
$$;

-- ── How many recovery codes are left ───────────────────────────────────────
-- Shown to the user after a recovery login, because "you have two left" is the
-- only thing that makes someone generate more before they run out.
CREATE OR REPLACE FUNCTION app_mfa_recovery_remaining(p_user_id uuid)
RETURNS integer
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT count(*)::int FROM user_recovery_codes
  WHERE user_id = p_user_id AND used_at IS NULL
$$;

REVOKE ALL ON FUNCTION app_mfa_begin(uuid, uuid, text, timestamptz, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_mfa_resolve(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_mfa_record_attempt(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_mfa_complete(uuid, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_mfa_consume_recovery(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_mfa_recovery_remaining(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION app_mfa_begin(uuid, uuid, text, timestamptz, text, text) TO meridian_app;
GRANT EXECUTE ON FUNCTION app_mfa_resolve(text) TO meridian_app;
GRANT EXECUTE ON FUNCTION app_mfa_record_attempt(uuid) TO meridian_app;
GRANT EXECUTE ON FUNCTION app_mfa_complete(uuid, bigint) TO meridian_app;
GRANT EXECUTE ON FUNCTION app_mfa_consume_recovery(uuid, text) TO meridian_app;
GRANT EXECUTE ON FUNCTION app_mfa_recovery_remaining(uuid) TO meridian_app;

-- Same assertion the auth surface carries: a definer function without a pinned
-- search_path can be redirected at a table the caller controls.
DO $$
DECLARE
  v_bad text;
BEGIN
  SELECT string_agg(p.proname, ', ') INTO v_bad
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.proname LIKE 'app_mfa_%'
    AND p.prosecdef
    AND (p.proconfig IS NULL OR NOT EXISTS (
      SELECT 1 FROM unnest(p.proconfig) c WHERE c LIKE 'search_path=%'
    ));

  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'SECURITY DEFINER function(s) without a pinned search_path: %', v_bad;
  END IF;
END;
$$;
